// financialActionTypes.ts
export const FETCH_FINANCIAL_STATISTICS_REQUEST = 'FETCH_FINANCIAL_STATISTICS_REQUEST';
export const FETCH_FINANCIAL_STATISTICS_SUCCESS = 'FETCH_FINANCIAL_STATISTICS_SUCCESS';
export const FETCH_FINANCIAL_STATISTICS_FAILURE = 'FETCH_FINANCIAL_STATISTICS_FAILURE';